//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2Demo.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ActivaEvaluacionCRUD
    {
       

        public int IdActiva { get; set; }
        public string NotaCodigo { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> ProcesoMatricula { get; set; }
        public Nullable<int> IdUsuario { get; set; }

        //[DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> Visible { get; set; }
    }
}
